/**
 *  class in java server for serialization
 */
export const ClassNameMap = {
  Person: 'Person',
  Company: 'Company',
  Employee: 'Employee',
  User: 'User',
  BusinessOwner: 'BusinessOwner',
  BusinessUnit: 'BusinessUnit',
  City: 'City',
  Nameable: 'Nameable',
  TaggedValue: 'TaggedValue',
  bankAccount: 'BankAccount',
  FinancialOperation: 'FinancialOperation',
  BankFinancialOperation: 'BankFinancialOperation',
  CashDeskFinancialOperation: 'CashDeskFinancialOperation',
  FinancialTransferWorkflowItem: 'FinancialTransferWorkflowItem',
  CashDeskAttribution: 'CashDeskAttribution',
  CashDesk: 'CashDesk',
  Document: 'Document',
  FinancialTransferType: 'FinancialTransferType',
  EmployeeFinancialOperation: 'EmployeeFinancialOperation',
  Account: 'Account',
  Dossier: 'Dossier',
  AccountFamily: 'AccountFamily',
  AccountingYear: 'AccountingYear',
  Journal: 'Journal',
  JournalFamily: 'JournalFamily',
  CompanyAccountingFolder: 'CompanyAccountingFolder',
  VatType: 'VatType',
  Country: 'Country',
  Operation: 'Operation',
  Purchase: 'Purchase',
  CashDeskOperationSales: 'CashDeskOperationSales',
  OperationFamily: 'OperationFamily',
  Bill: 'Bill',
  BillOrder: 'BillOrder',
  ProductOrder: 'ProductOrder',
  ProductOrderItem: 'ProductOrderItem',
  ProductOrderDiscount: 'ProductOrderDiscount',
  ProductOrderCredit: 'ProductOrderCredit',
  CashDeskOperation: 'CashDeskOperation',
  OperationDocument: 'OperationDocument',
  Supplier: 'Supplier',
  Customer: 'Customer',
  AccountingPeriod: 'AccountingPeriod',
  AccountingChart: 'AccountingChart',
  ProductFamily: 'ProductFamily',
  CustomProductFamily: 'ProductFamily',
  Rubric: 'Rubric',
  Bloc: 'Bloc',
  Report: 'Report',
  ProductFamilyParameters: 'ProductFamilyParameters',
  VatRubric: 'VatRubric',
  VatDeclarationReport: 'VatDeclarationReport',
  CameroonVatDeclarationReport: 'CameroonVatDeclarationReport',
  AccountEntry: 'AccountEntry',
  ProductSupplier: 'ProductSupplier',
  Product: 'Product',
  OrderItem: 'OrderItem',
  Invoice: 'Invoice',
  Bank: 'Bank',
  Prospect: 'Prospect',
  Statement: 'Statement',
  ReportEntity: 'ReportEntity',
  ReportsParameters: 'ReportsParameters'
};
/**
 * Correspondance between functionality name as define in angular,
 * and those define in the server
 * key = funtionality in angular
 * value = functionality in java server
 */
export const FunctionnalityMap = {
  MoneyTransfer: 'MONEY_TRANSFER',
  MoneyTransferUserDashboard: 'MONEY_TRANSFER_DASHBOARD_USER',
  MoneyTransferAllDashboard: 'MONEY_TRANSFER_DASHBOARD_GENERAL',
  FinancialOperation: 'MONEY_TRANSFER',
  FinancialOperationList: 'MONEY_TRANSFER_LIST_ALL',
  FinancialOperationListOwn: 'MONEY_TRANSFER_LIST_OWN',
  FinancialOperationShow: 'MONEY_TRANSFER',
  FinancialWorkflowItemShow: 'MONEY_TRANSFER',
  FinancialWorkflowItemEdit: 'MONEY_TRANSFER',
  ConfirmFinancialWorkflowItemEdit: 'MONEY_TRANSFER',
  ConfirmBankFinancialOperation: 'BANK_MONEY_TRANSFER_CONFIRM',
  CashDeskAttribution: 'CASH_DESK_ATTRIBUTION',
  CashDeskAttributionEdit: 'CASH_DESK_ATTRIBUTION',
  CashDeskAttributionList: 'CASH_DESK_ATTRIBUTION',
  CashDeskAttributionShow: 'CASH_DESK_ATTRIBUTION',
  ToCashDeskFinancialOperationEdit: 'TO_CASHDESK_MONEY_TRANSFER',
  FromCashDeskFinancialOperationEdit: 'FROM_CASHDESK_MONEY_TRANSFER',
  ToBankFinancialOperationEdit: 'TO_BANK_MONEY_TRANSFER',
  FromBankFinancialOperationEdit: 'FROM_BANK_MONEY_TRANSFER',
  ToSecretaryFinancialOperationEdit: 'TO_SECRETARY_MONEY_TRANSFER',
  FromSecretaryFinancialOperationEdit: 'FROM_SECRETARY_MONEY_TRANSFER',
  FinancialStatement: 'FINANCIAL_STATUS_REPORT',
  FinancialStatementList: 'FINANCIAL_STATUS_REPORT',
  Organisation: 'Organisation',
  Bank: 'BANK',
  BankList: 'BANK',
  BankEdit: 'BANK',
  BankShow: 'BANK',
  BankAccount: 'BANK_ACCOUNT',
  BankAccountEdit: 'BANK_ACCOUNT',
  BankAccountList: 'BANK_ACCOUNT',
  BankAccountShow: 'BANK_ACCOUNT',
  Administration: 'Administration',
  ParametersEdit: 'FINANCIAL_MODULE_PARAMETERS',
  ParametersShow: 'FINANCIAL_MODULE_PARAMETERS',
  Parameters: 'FINANCIAL_MODULE_PARAMETERS',
  UserParameters: 'EMPLOYEE.PASSWORD',
  UserParametersEdit: 'EMPLOYEE.PASSWORD',
  UserParametersShow: 'EMPLOYEE.PASSWORD',
  BusinessOwnerEdit: 'BusinessOwnerEdit',
  Account: 'Account',
  AccountShow: 'AccountShow',
  AccountFamily: 'AccountFamily',
  AccountFamilyShow: 'AccountFamilyShow',
  AccountingYear: 'AccountingYear',
  AccountingYearIndex: 'AccountingYearIndex',
  AccountingYearShow: 'AccountingYearShow',
  Journal: 'Journal',
  JournalIndex: 'JournalIndex',
  JournalShow: 'JournalShow',
  CompanyAccountingFolder: 'CompanyAccountingFolder',
  VatType: 'VatType',
  VatTypeIndex: 'VatTypeIndex',
  VatTypeShow: 'VatTypeShow',
  Country: 'Country',
  Operation: 'Operation',
  OperationFamily: 'OperationFamily',
  PurchaseOperation: 'PurchaseOperation',
  SaleOperation: 'SaleOperation',
  GeneralBillEdit: 'GeneralBillEdit',
  GeneralBillList: 'GeneralBillList',
  CountryIndex: 'CountryIndex',
  CountryShow: 'CountryShow',
  AccountingChartParams: 'AccountingChartParams',
  OperationFamilyForm: 'OperationFamilyForm',
  OperationFamilyList: 'OperationFamilyList',
  OperationFamilyShow: 'OperationFamilyShow',
  AccountingPeriod: 'AccountingPeriod',
  ReportParametersEdit: 'ReportParametersEdit'
};


/**
 * Association between menu/functionality and module
 * key = menu name in angular
 * value = list of modules in java server
 */
export const MenuModulesMap = {
  MoneyTransfer: ['FINANCIAL_MODULE'],
  MoneyTransferUserDashboard: ['FINANCIAL_MODULE'],
  MoneyTransferAllDashboard: ['FINANCIAL_MODULE'],
  FinancialOperation: ['FINANCIAL_MODULE'],
  FinancialOperationList: ['FINANCIAL_MODULE'],
  FinancialOperationShow: ['FINANCIAL_MODULE'],
  FinancialWorkflowItemShow: ['FINANCIAL_MODULE'],
  FinancialWorkflowItemEdit: ['FINANCIAL_MODULE'],
  ConfirmBankFinancialOperation:['FINANCIAL_MODULE'],
  CashDeskAttribution: ['FINANCIAL_MODULE'],
  ToCashDeskFinancialOperationEdit: ['FINANCIAL_MODULE'],
  FromCashDeskFinancialOperationEdit: ['FINANCIAL_MODULE'],
  ToBankFinancialOperationEdit: ['FINANCIAL_MODULE'],
  FromBankFinancialOperationEdit: ['FINANCIAL_MODULE'],
  ToSecretaryFinancialOperationEdit: ['FINANCIAL_MODULE'],
  FromSecretaryFinancialOperationEdit: ['FINANCIAL_MODULE'],
  FinancialStatement: ['FINANCIAL_MODULE'],
  Organisation: ['FINANCIAL_MODULE'],
  Bank: ['FINANCIAL_MODULE'],
  BankAccount: ['FINANCIAL_MODULE'],
  Administration: ['FINANCIAL_MODULE'],
  Parameters: ['FINANCIAL_MODULE'],
  BusinessOwnerEdit: ['FINANCIAL_MODULE'],
  Account: ['FINANCIAL_MODULE'],
  AccountShow: ['FINANCIAL_MODULE'],
  AccountFamily: ['FINANCIAL_MODULE'],
  AccountFamilyShow: ['FINANCIAL_MODULE'],
  AccountingYear: ['FINANCIAL_MODULE'],
  AccountingYearIndex: ['FINANCIAL_MODULE'],
  AccountingYearShow: ['FINANCIAL_MODULE'],
  Journal: ['FINANCIAL_MODULE'],
  JournalIndex: ['FINANCIAL_MODULE'],
  JournalShow: ['FINANCIAL_MODULE'],
  PurchaseOperation: ['FINANCIAL_MODULE'],
  SaleOperation: ['FINANCIAL_MODULE'],
  CompanyAccountingFolder: ['FINANCIAL_MODULE'],
  VatType: ['FINANCIAL_MODULE'],
  VatTypeIndex: ['FINANCIAL_MODULE'],
  VatTypeShow: ['FINANCIAL_MODULE'],
  Country: ['FINANCIAL_MODULE'],
  Operation: ['FINANCIAL_MODULE'],
  OperationFamily: ['FINANCIAL_MODULE'],
  CountryIndex: ['FINANCIAL_MODULE'],
  CountryShow: ['FINANCIAL_MODULE'],
  AccountingChartParams: ['FINANCIAL_MODULE'],
  OperationFamilyForm: ['FINANCIAL_MODULE'],
  OperationFamilyList: ['FINANCIAL_MODULE'],
  OperationFamilyShow: ['FINANCIAL_MODULE'],
  AccountingPeriod: ['FINANCIAL_MODULE']

};

/**
 * Correspondance between action name as define in angular,
 * and those define in the server
 * key = action in angular
 * value = action in java server
 */
export const ActionMap = {
  ALL: 'ALL',
  CREATE: 'CREATE',
  CREATE_CHILD: 'CREATE',
  CREATE_A_COPY: 'CREATE',
  ADD_NEW: 'CREATE',
  LIST: 'VIEW',
  SHOW: 'VIEW',
  READ: 'VIEW',
  ADD: 'ADD',
  UPDATE: 'EDIT',
  DELETE: 'DELETE',
  SAVE: 'EDIT',
  VALIDATE: 'EDIT',
  SEND_MAIL: 'SEND_MAIL',
  CLOSE: 'EDIT',
  PREV: 'PREV',
  NEXT: 'NEXT',
  PRINT: 'PRINT',
  REJECT: 'EDIT'
};
